Repository sporestudio/hiddenbox, pull requests merged in 2025-05, with the labels that each got.

#23 refactor: Remove Redis dependency
  app/backend/src/lib/__init__.py
  app/backend/src/lib/crypto.py
Labels: refactor

#25 refactor: Create datatypes
  app/backend/src/lib/__init__.py
  app/backend/src/lib/crypto.py
  app/backend/src/lib/datatypes.py
Labels: refactor

#30 refactor: Create unitary test for Crypto service
  pytest.ini
  tests/unit/test_crypto.py
Labels: tests

#42 refactor: Normalize crypto library
  app/backend/src/lib/crypto.py
  tests/unit/test_crypto.py
Labels: refactor

#43 feature: Integrate tests with pre-commit and GitHub actions
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  app/backend/src/lib/__init__.py
  app/backend/src/lib/crypto.py
  app/backend/src/lib/datatypes.py
  app/backend/src/lib/redis_service.py
  app/backend/src/main.py
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/unit/test_crypto.py
Labels: tests

#48 refactor: Adapt Crypto to be used as a singleton
  app/backend/src/lib/crypto.py
  tests/unit/test_crypto.py
Labels: refactor

#51 feature: Create login
  app/frontend/public/assets/hiddenbox-logo.png
  app/frontend/public/assets/react.svg
  app/frontend/src/components/Header.tsx
  app/frontend/src/components/LoginCard.tsx
  app/frontend/src/components/Photo.tsx
  app/frontend/src/pages/login.tsx
Labels: feature

#52 refactor: Fix login
  app/frontend/src/context/AuthContext.tsx
  app/frontend/src/pages/dashboard.tsx
  app/frontend/src/pages/login.tsx
Labels: fix

#59 Refactor: dashboard styles
  src/web/src/components/Header.tsx
  src/web/src/index.css
  src/web/src/layouts/BaseLayout.tsx
  src/web/src/pages/dashboard.tsx
Labels: refactor

#64 feature: Deploy s3 buckets
  main.tf
  variables.tf
Labels: feature

#66 docs: Update readme
  README.md
  docs/CONTRIBUTING.md
  docs/assets/imgs/hiddenbox-architecture.svg
  docs/assets/imgs/hiddenbox-colors.png
  docs/assets/imgs/hiddenbox-logo-neg.png
  docs/assets/imgs/hiddenbox-logo-size.png
  docs/assets/imgs/hiddenbox-logo.png
  docs/assets/imgs/hiddenbox-variety.png
Labels: documentation

#72 fix: Solve download logic on api
  src/api/lib/datatypes.py
  src/api/main.py
Labels: fix

#73 fix: Solve bugs infra
  compose.yml
  main.tf
  variables.tf
Labels: fix
